--1--
SELECT name, open_mode, con_id FROM v$pdbs;

--2--
SELECT * FROM V$INSTANCE;

--3-
SELECT comp_name, status, VERSION FROM DBA_REGISTRY;

SELECT * FROM user$

--4--
create tablespace PEV_pdb 
datafile 'D:\app\oracleuser\oradata\TEST\ts_pdb.dbf' 
size 7 m 
autoextend on next 5m 
maxsize 20m 
extent management local;

--5--
SELECT * FROM v$services;

ALTER DATABASE TEST OPEN;

--6-- 
CREATE TABLESPACE PEV_DB_SPACE
DATAFILE 'D:\app\oracleuser\oradata\TEST\PEV_DB_SPACE.dat'
SIZE 10M
AUTOEXTEND ON NEXT 5M
MAXSIZE 30M;

CREATE ROLE PEV_role;

CREATE PROFILE PEV_PROFILE
 LIMIT
  PASSWORD_LIFE_TIME 180
  SESSIONS_PER_USER 3
  FAILED_LOGIN_ATTEMPTS 7
  PASSWORD_LOCK_TIME 1
  PASSWORD_REUSE_TIME 10
  PASSWORD_GRACE_TIME 7
  CONNECT_TIME 180
  IDLE_TIME 30;
  
CREATE USER U1_PEV_PDB
IDENTIFIED BY Stearis
DEFAULT TABLESPACE PEV_DB_SPACE
PROFILE PEV_PROFILE
ACCOUNT UNLOCK;
  
GRANT CREATE TABLE, CREATE SESSION TO U1_PEV_PDB;

ALTER USER U1_PEV_PDB QUOTA 2M ON PEV_DB_SPACE

--7--
CREATE TABLE PEV_table
(id int,
name varchar(50)
)

INSERT INTO PEV_table
VALUES (1,'First');

INSERT INTO PEV_table
VALUES (2,'Second');

INSERT INTO PEV_table
VALUES (3,'Third');

SELECT * FROM PEV_table

COMMIT

--8--
SELECT TABLESPACE_NAME FROM dba_tablespaces

SELECT file_name FROM dba_data_files

SELECT * FROM dba_roles;

SELECT  * FROM dba_sys_privs ORDER BY GRANTEE

SELECT * FROM DBA_PROFILES;

SELECT * FROM DBA_USERS

--9--
CREATE USER PEV
IDENTIFIED BY 111
PROFILE DEFAULT
ACCOUNT UNLOCK

CREATE USER MVS
IDENTIFIED BY 222
PROFILE DEFAULT
ACCOUNT UNLOCK

GRANT CREATE SESSION, CONNECT TO PEV

GRANT CREATE SESSION TO MVS

--11--
SELECT * FROM v$session

SELECT * FROM DBA_USERS

--13--
ALTER pluggable database TEST 'D:\app\oracleuser\oradata\TEST\pdb_a.xml'

DROP pluggable database TEST

DROP USER PEV;

DROP USER MVS;




