CREATE OR REPLACE TRIGGER  TEACH_BEFORE_UPDATE
BEFORE UPDATE ON TEACHER
BEGIN
DBMS_OUTPUT.PUT_LINE('BEFORE UPDATE');
END;
UPDATE TEACHER SET  SALARY=1001 WHERE TEACHER='œœœœ';

CREATE OR REPLACE TRIGGER  TEACH_BEFORE_INSERT
BEFORE INSERT ON TEACHER
BEGIN
DBMS_OUTPUT.PUT_LINE('BEFORE INSERT');
END;
INSERT INTO TEACHER VALUES('œ–÷ ','œœ–Œ÷” Œ¬»◊  »–»ÀÀ Ã»’¿…ÀŒ¬»◊','Ï','»—Ë“','28.05.1999',300);

CREATE OR REPLACE TRIGGER  TEACH_BEFORE_DELETE
BEFORE DELETE ON TEACHER
BEGIN
DBMS_OUTPUT.PUT_LINE('BEFORE DELETE');
END;
DELETE TEACHER WHERE TEACHER='œ–÷ ';
------
CREATE OR REPLACE TRIGGER   TEACH_BEFORE_UPDATE_ROWS
BEFORE UPDATE  ON  TEACHER
FOR EACH ROW
BEGIN
INSERT INTO AUDITT VALUES('UPDATE','TEACH_BEFORE_UPDATE',:old.SALARY||' '||:new.SALARY);
DBMS_OUTPUT.PUT_LINE('BEFORE UPDATE ROWS');
END;
UPDATE TEACHER SET  SALARY=SALARY+10 WHERE PULPIT='»—Ë“';
SELECT * FROM AUDITT

CREATE OR REPLACE TRIGGER  TEACH_BEFORE_INSERT_ROWS
BEFORE INSERT ON TEACHER
FOR EACH ROW
BEGIN
INSERT INTO AUDITT VALUES('INSERT','TEACH_BEFORE_INSERT',:old.SALARY||' '||:new.SALARY);
DBMS_OUTPUT.PUT_LINE('BEFORE INSERT ROWS');
END;
INSERT INTO TEACHER VALUES('œ–÷ ','œœ–Œ÷” Œ¬»◊  »–»ÀÀ Ã»’¿…ÀŒ¬»◊','Ï','»—Ë“','28.05.1999',300);

CREATE OR REPLACE TRIGGER  TEACH_BEFORE_DELETE_ROWS
BEFORE DELETE ON TEACHER
FOR EACH ROW
BEGIN
INSERT INTO AUDITT VALUES('DELETE','TEACH_BEFORE_DELETE',:old.SALARY||' '||:new.SALARY);
DBMS_OUTPUT.PUT_LINE('BEFORE DELETE ROWS');
END;
DELETE TEACHER WHERE TEACHER='œ–÷ ' OR TEACHER='œ–÷ 2';
-----------------
CREATE OR REPLACE TRIGGER  TEACH_BEFORE_ALL
BEFORE DELETE OR INSERT OR UPDATE ON TEACHER
BEGIN
IF INSERTING THEN
DBMS_OUTPUT.PUT_LINE('ALL INSERT'); END IF;
IF DELETING THEN
DBMS_OUTPUT.PUT_LINE('ALL DELETE'); END IF;
IF UPDATING THEN
DBMS_OUTPUT.PUT_LINE('ALL UPDATE'); END IF;
END;

DELETE TEACHER WHERE TEACHER='œ–÷ ' OR TEACHER='œ–÷ 2';
------------------
CREATE OR REPLACE TRIGGER  TEACH_AFTER_UPDATE
AFTER UPDATE ON TEACHER
BEGIN

DBMS_OUTPUT.PUT_LINE('AFTER UPDATE');
END;
UPDATE TEACHER SET  SALARY=1001 WHERE TEACHER='œœœœ';

CREATE OR REPLACE TRIGGER  TEACH_AFTER_INSERT
AFTER INSERT ON TEACHER
BEGIN
DBMS_OUTPUT.PUT_LINE('AFTER INSERT');
END;
INSERT INTO TEACHER VALUES('œ–÷ ','œœ–Œ÷” Œ¬»◊  »–»ÀÀ Ã»’¿…ÀŒ¬»◊','Ï','»—Ë“','28.05.1999',300);

CREATE OR REPLACE TRIGGER  TEACH_AFTER_DELETE
AFTER DELETE ON TEACHER
BEGIN
DBMS_OUTPUT.PUT_LINE('AFTER DELETE');
END;
DELETE TEACHER WHERE TEACHER='œ–÷ ';
------
CREATE OR REPLACE TRIGGER   TEACH_AFTER_UPDATE_ROWS
AFTER UPDATE  ON  TEACHER
FOR EACH ROW
BEGIN
INSERT INTO AUDITT VALUES('UPDATE','TEACH_AFTER_UPDATE',:old.SALARY||' '||:new.SALARY);
DBMS_OUTPUT.PUT_LINE('AFTER UPDATE ROWS');
END;
UPDATE TEACHER SET  SALARY=SALARY+10 WHERE PULPIT='»—Ë“';

CREATE OR REPLACE TRIGGER  TEACH_AFTER_INSERT_ROWS
AFTER INSERT ON TEACHER
FOR EACH ROW
BEGIN
INSERT INTO AUDITT VALUES('INSERT','TEACH_AFTER_INSERT',:old.SALARY||' '||:new.SALARY);
DBMS_OUTPUT.PUT_LINE('AFTER INSERT ROWS');
END;
INSERT INTO TEACHER VALUES('œ–÷ ','œœ–Œ÷” Œ¬»◊  »–»ÀÀ Ã»’¿…ÀŒ¬»◊','Ï','»—Ë“','28.05.1999',300);

CREATE OR REPLACE TRIGGER  TEACH_AFTER_DELETE_ROWS
AFTER DELETE ON TEACHER
FOR EACH ROW
BEGIN
INSERT INTO AUDITT VALUES('DELETE','TEACH_AFTER_DELETE',:old.SALARY||' '||:new.SALARY);
DBMS_OUTPUT.PUT_LINE('AFTER DELETE ROWS');
END;
DELETE TEACHER WHERE TEACHER='œ–÷ ' OR TEACHER='œ–÷ 2';
-----------------------
CREATE TABLE AUDITT
(
OperationType varchar(100),
TriggerName varchar(100),
DataT varchar(100)
)
SELECT * FROM TEACHER
DELETE FROM AUDITT

INSERT INTO TEACHER VALUES('œ–÷ ','œœ–Œ÷” Œ¬»◊  »–»ÀÀ Ã»’¿…ÀŒ¬»◊','Ï','»—Ë“','28.05.1999',300);
DELETE FROM TEACHER WHERE TEACHER='œ–÷ '
SELECT * FROM AUDITT

CREATE OR REPLACE TRIGGER  TEACH_DELL
BEFORE DROP ON SYSTEM.SCHEMA
BEGIN
DBMS_OUTPUT.PUT_LINE('ERROR DROP');
END;

CREATE TABLE KKK
( ID INT)
DROP TABLE KKK




SELECT * FROM AUDITT

CREATE VIEW VTEATHER
AS SELECT TEACHER UA
FROM TEACHER

SELECT * FROM VTEATHER

CREATE OR REPLACE TRIGGER TTEATHER
INSTEAD OF INSERT ON VTEATHER
BEGIN 
INSERT INTO TEACHER VALUES('œ–÷ ','œœ–Œ÷” Œ¬»◊  »–»ÀÀ Ã»’¿…ÀŒ¬»◊','Ï','»—Ë“','28.05.1999',300);
END;
  
INSERT INTO VTEATHER (UA) VALUES ('œ–Œ');