CREATE OR REPLACE PROCEDURE GET_TEACHERS(CODE TEACHER.PULPIT%TYPE)
IS
CURSOR CUR_TEACH
IS SELECT TEACHER,TEACHER_NAME,GENDER,PULPIT,BIRTHDAY,SALARY FROM TEACHER;
CC_SUB TEACHER%ROWTYPE;
BEGIN
OPEN CUR_TEACH;
FETCH CUR_TEACH INTO CC_SUB;
WHILE CUR_TEACH%FOUND
LOOP
IF CC_SUB.PULPIT=CODE THEN DBMS_OUTPUT.PUT_LINE(CC_SUB.TEACHER||CC_SUB.TEACHER_NAME); END IF;
FETCH CUR_TEACH INTO CC_SUB;
END LOOP;
CLOSE CUR_TEACH;
END GET_TEACHERS;

BEGIN
GET_TEACHERS('»—Ë“');
END;
-----------------------------
CREATE OR REPLACE FUNCTION GET_TEACHERSS(CODE TEACHER.PULPIT%TYPE)
RETURN NUMBER IS
CURSOR CUR_TEACH
IS SELECT TEACHER,TEACHER_NAME,GENDER,PULPIT,BIRTHDAY,SALARY FROM TEACHER;
CC_SUB TEACHER%ROWTYPE;
COUNTS NUMBER:=0;
BEGIN
OPEN CUR_TEACH;
FETCH CUR_TEACH INTO CC_SUB;
WHILE CUR_TEACH%FOUND
LOOP
IF CC_SUB.PULPIT=CODE THEN COUNTS:=COUNTS+1;  END IF;
FETCH CUR_TEACH INTO CC_SUB;
END LOOP;
CLOSE CUR_TEACH;
RETURN COUNTS;
END GET_TEACHERSS;

DECLARE
X NUMBER;
BEGIN
X:=GET_TEACHERSS('À¬');
DBMS_OUTPUT.PUT_LINE('COUNT='||X);
END; 
---------------------
 CREATE OR REPLACE PROCEDURE GET_SUBJECT(CODE SUBJECT.PULPIT%TYPE)
IS
CURSOR CUR_TEACH
IS SELECT SUBJECT,SUBJECT_NAME,PULPIT FROM SUBJECT;
CC_SUB SUBJECT%ROWTYPE;
BEGIN
OPEN CUR_TEACH;
FETCH CUR_TEACH INTO CC_SUB;
WHILE CUR_TEACH%FOUND
LOOP
IF CC_SUB.PULPIT=CODE THEN DBMS_OUTPUT.PUT_LINE(CC_SUB.SUBJECT_NAME); END IF;
FETCH CUR_TEACH INTO CC_SUB;
END LOOP;
CLOSE CUR_TEACH;
END GET_SUBJECT;

BEGIN
GET_SUBJECT('»—Ë“');
END;
--------------------------
CREATE OR REPLACE FUNCTION GET_NUM_TEACHERSS(CODE FACULTY.FACULTY%TYPE)
RETURN NUMBER IS
CURSOR CUR_TEACH
IS SELECT TEACHER,TEACHER_NAME,GENDER,PULPIT,BIRTHDAY,SALARY FROM TEACHER;
CC_SUB TEACHER%ROWTYPE;
COUNTS NUMBER:=0;
CURSOR CUR_SUB
IS SELECT PULPIT,PULPIT_NAME,FACULTY FROM PULPIT;
CC_SUB2 PULPIT%ROWTYPE;
BEGIN
OPEN CUR_TEACH;
FETCH CUR_TEACH INTO CC_SUB;
WHILE CUR_TEACH%FOUND
LOOP
OPEN CUR_SUB;
FETCH CUR_SUB INTO CC_SUB2;
WHILE CUR_SUB%FOUND
LOOP
IF CC_SUB2.FACULTY=CODE AND CC_SUB2.PULPIT=CC_SUB.PULPIT THEN COUNTS:=COUNTS+1;  END IF;
FETCH CUR_SUB INTO CC_SUB2;
END LOOP;
CLOSE CUR_SUB;

FETCH CUR_TEACH INTO CC_SUB;
END LOOP;
CLOSE CUR_TEACH;
RETURN COUNTS;
END GET_NUM_TEACHERSS;

DECLARE
X NUMBER;
BEGIN
X:=GET_NUM_TEACHERSS('À’‘');  --»ƒËœ À’‘
DBMS_OUTPUT.PUT_LINE('COUNT='||X);
END; 
--------------------------------
CREATE OR REPLACE
PACKAGE PACK AS
TYPE TECH IS RECORD
(
 FF FACULTY.FACULTY%TYPE,
 SB SUBJECT.PULPIT%TYPE,
 TP TEACHER.PULPIT%TYPE
);
EXC_FF EXCEPTION;
EXC_SB EXCEPTION;
EXC_TP EXCEPTION;
PROCEDURE  GET_SUBJECT(TR TECH);
PROCEDURE  GET_TEACHERS(TR TECH);
FUNCTION GET_NUM_TEACHERSS(TR TECH) RETURN BOOLEAN;
FUNCTION GET_TEACHERSS(TR TECH) RETURN BOOLEAN;
END PACK;


DECLARE
REC PACK.TECH;
BEGIN
REC.FF:='»ƒËœ';
REC.SB:='»—Ë“';
REC.TP:='»—Ë“';
PACK.GET_SUBJECT(REC);
END;