---RANGE(ƒ»¿œ¿«ŒÕÕŒ≈)
CREATE TABLE T_RANGE
(
  PER NUMBER
)
PARTITION BY RANGE (PER)
(
PARTITION RANGE1 VALUES LESS THAN (10),
PARTITION RANGE2 VALUES LESS THAN (20),
PARTITION RANGE3 VALUES LESS THAN (MAXVALUE)
);
INSERT INTO T_RANGE VALUES(5);
INSERT INTO T_RANGE VALUES(15);
INSERT INTO T_RANGE VALUES(42);

select * from T_RANGE

SELECT * FROM T_RANGE PARTITION (RANGE1A);
SELECT * FROM T_RANGE PARTITION (RANGE1B);
SELECT * FROM T_RANGE PARTITION (RANGE2);
SELECT * FROM T_RANGE PARTITION (RANGE3);


--
ALTER TABLE T_RANGE ENABLE ROW MOVEMENT;
UPDATE  T_RANGE PARTITION(RANGE2)
SET PER=PER-5;
--
ALTER TABLE T_RANGE EXCHANGE PARTITION RANGE3
WITH TABLE ZZZ WITHOUT VALIDATION;

CREATE TABLE ZZZ
(
  Z NUMBER
)
SELECT * FROM ZZZ

INSERT INTO T_RANGE VALUES(9);
-----SPIT

ALTER TABLE T_RANGE SPLIT PARTITION RANGE1
AT (8) INTO
(
PARTITION RANGE1A,
PARTITION RANGE1B
)

------------------

---INTERVAL
CREATE TABLE T_INTERVAL
(
  PER2 DATE
)
PARTITION BY RANGE(PER2)
INTERVAL  (NUMTOYMINTERVAL (1,'YEAR'))
(
  PARTITION INTERVAL1 VALUES LESS THAN ('01.01.2015')
);

SELECT * FROM T_INTERVAL

INSERT INTO T_INTERVAL VALUES('05.01.2015');
INSERT INTO T_INTERVAL VALUES('25.03.2018');

SELECT * FROM T_INTERVAL PARTITION FOR ('05.05.2018');
SELECT * FROM T_INTERVAL PARTITION FOR ('20.01.2015');



------HASH
CREATE TABLE T_HASH
(
STR VARCHAR2(15)
)
PARTITION BY HASH(STR)
PARTITIONS 16

INSERT INTO T_HASH VALUES('HELLO');
INSERT INTO T_HASH VALUES('WORLD');
INSERT INTO T_HASH VALUES('!!!');

SELECT * FROM T_HASH      ----???????????
----------
---LIST
CREATE TABLE T_LIST
(
STR CHAR(15)
)
PARTITION BY LIST (STR)
(
PARTITION X1 VALUES('A'),
PARTITION X2 VALUES('AA'),
PARTITION X3 VALUES(DEFAULT)
)
 
 INSERT INTO T_LIST VALUES('B');
 INSERT INTO T_LIST VALUES('ASD');
 INSERT INTO T_LIST VALUES('AA');
 INSERT INTO T_LIST VALUES('A');
 
 
 
 SELECT * FROM T_LIST;
SELECT * FROM T_LIST PARTITION (X12);
SELECT * FROM T_LIST PARTITION (X3);


ALTER TABLE T_LIST MERGE PARTITIONS
 X1, X2 INTO PARTITION X12;